### ISSUE TITLE
Error: Something went wrong while executing your query

### ISSUE THREAD

**Issue by Mr-KayJayDee** [teoxoy/profile-readme-stats#6]
Here the screenshot of the error.

![image](https://user-images.githubusercontent.com/46600662/115282975-1a40b700-a14b-11eb-8485-66d1974b9da6.png)

The code they are asking to give:
`
07C2:4FCA:E5D17F:29EBB3A:607DC6CE
`

And my workflow config:

```yml
on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4 # here i just added the latest actions/checkout version because the v2 wasn't working
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update README.md statistics
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
```
